.TH "src Directory Reference" 3 "Tue Apr 19 2016" "Andrew and Nick's Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBdefinitions\&.hpp\fP"
.br
.RI "\fIContains declarations of system-independant (universal size) integers and float types, shortened type names for some commonly used types, and enumerations\&. \fP"
.ti -1c
.RI "file \fBfileio\&.hpp\fP"
.br
.RI "\fIcontains functions related to the file I/O use in this program \fP"
.ti -1c
.RI "file \fBfileio_test\&.cpp\fP"
.br
.RI "\fIContains program that tests the functions in \fBfileio\&.hpp\fP\&. \fP"
.ti -1c
.RI "file \fBmain\&.cpp\fP"
.br
.RI "\fIcontains the main program \fP"
.ti -1c
.RI "file \fBpatient_name_test\&.cpp\fP"
.br
.RI "\fIContains a program to test the \fBPatientName()\fP function\&. \fP"
.ti -1c
.RI "file \fBprocess\&.hpp\fP"
.br
.RI "\fIContains functions related to the program's threaded processing of audio data\&. \fP"
.ti -1c
.RI "file \fBprocess_test\&.cpp\fP"
.br
.RI "\fIContains a program to test the \fBprocess()\fP function\&. \fP"
.ti -1c
.RI "file \fBread_params_test\&.cpp\fP"
.br
.RI "\fIContains a program test the \fBPatientName()\fP function\&. \fP"
.ti -1c
.RI "file \fBsigmath\&.hpp\fP"
.br
.RI "\fIcontains the functions necessary to perform the mathematical operations required by this program \fP"
.ti -1c
.RI "file \fBsound\&.hpp\fP"
.br
.RI "\fIcontains the function(s) relating to sound \fP"
.ti -1c
.RI "file \fBstdin_clear_test\&.cpp\fP"
.br
.RI "\fIContains a program to test clearing the stdin buffer\&. \fP"
.in -1c
