.TH "src Directory Reference" 3 "Mon Apr 18 2016" "Andrew and Nick's Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBdefinitions\&.hpp\fP"
.br
.ti -1c
.RI "file \fBfileio\&.hpp\fP"
.br
.RI "\fIcontains functions related to the file I/O use in this program \fP"
.ti -1c
.RI "file \fBmain\&.cpp\fP"
.br
.RI "\fIcontains the main program \fP"
.ti -1c
.RI "file \fBpatient_name_test\&.cpp\fP"
.br
.ti -1c
.RI "file \fBprocess\&.hpp\fP"
.br
.ti -1c
.RI "file \fBprocess_test\&.cpp\fP"
.br
.ti -1c
.RI "file \fBsigmath\&.hpp\fP"
.br
.RI "\fIcontains the functions necessary to perform the mathematical operations required by this program \fP"
.ti -1c
.RI "file \fBsigmath_test\&.cpp\fP"
.br
.ti -1c
.RI "file \fBsound\&.hpp\fP"
.br
.in -1c
