.TH "src Directory Reference" 3 "Wed Mar 30 2016" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBdefinitions\&.hpp\fP"
.br
.ti -1c
.RI "file \fBfileio\&.hpp\fP"
.br
.ti -1c
.RI "file \fBmain\&.cpp\fP"
.br
.ti -1c
.RI "file \fBsigmath\&.hpp\fP"
.br
.ti -1c
.RI "file \fBsound\&.hpp\fP"
.br
.ti -1c
.RI "file \fBthreadproc\&.hpp\fP"
.br
.in -1c
