.TH "bug" 3 "Wed Apr 20 2016" "The Automatic Vasospasm Detection Application" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bug \- Bug List 

.IP "\fBFile \fBfileio\&.hpp\fP \fP" 1c
file is overly complicated and much more bug-prone  
.IP "\fBFile \fBmain\&.cpp\fP \fP" 1c
extra newline character inserted into stdin buffer after \fBPatientName()\fP is run 
.PP

