.TH "DataParams" 3 "Wed Mar 30 2016" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DataParams \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <definitions\&.hpp>\fP
.SH "Detailed Description"
.PP 
A structure containing the calculated results from processing the audio recordings\&. 
.PP
Definition at line 40 of file definitions\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
