.TH "DataParams" 3 "Fri Apr 15 2016" "Andrew and Nick's Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DataParams \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <definitions\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBfloat32\fP \fBfreq\fP"
.br
.ti -1c
.RI "\fBfloat32\fP \fBnoise\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Contains the calculated results from processing the audio recordings\&. 
.PP
Definition at line 44 of file definitions\&.hpp\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBfloat32\fP DataParams::freq"

.PP
Definition at line 45 of file definitions\&.hpp\&.
.SS "\fBfloat32\fP DataParams::noise"

.PP
Definition at line 46 of file definitions\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Andrew and Nick's Project from the source code\&.
