.TH "DataParams" 3 "Thu Mar 31 2016" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DataParams \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <definitions\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBfloat32\fP \fBfreq\fP"
.br
.ti -1c
.RI "\fBfloat32\fP \fBnois\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A structure containing the calculated results from processing the audio recordings\&. 
.PP
Definition at line 40 of file definitions\&.hpp\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBfloat32\fP DataParams::freq"

.PP
Definition at line 41 of file definitions\&.hpp\&.
.SS "\fBfloat32\fP DataParams::nois"

.PP
Definition at line 42 of file definitions\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
