.TH "src/definitions.hpp" 3 "Tue Apr 19 2016" "Andrew and Nick's Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/definitions.hpp \- 
.PP
Contains declarations of system-independant (universal size) integers and float types, shortened type names for some commonly used types, and enumerations\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <complex>\fP
.br
\fC#include <map>\fP
.br
\fC#include <string>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBDataParams\fP"
.br
.ti -1c
.RI "struct \fBMaximum\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBvaso\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBENUM\fP   signed char"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef unsigned char \fBbyte\fP"
.br
.ti -1c
.RI "typedef unsigned char \fBuint8\fP"
.br
.ti -1c
.RI "typedef signed char \fBsint8\fP"
.br
.ti -1c
.RI "typedef unsigned short \fBuint16\fP"
.br
.ti -1c
.RI "typedef signed short \fBsint16\fP"
.br
.ti -1c
.RI "typedef unsigned int \fBuint32\fP"
.br
.ti -1c
.RI "typedef signed int \fBsint32\fP"
.br
.ti -1c
.RI "typedef unsigned long long \fBuint64\fP"
.br
.ti -1c
.RI "typedef signed long long \fBsint64\fP"
.br
.ti -1c
.RI "typedef float \fBfloat32\fP"
.br
.ti -1c
.RI "typedef double \fBfloat64\fP"
.br
.ti -1c
.RI "typedef std::complex< \fBfloat32\fP > \fBcfloat32\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBvaso::Side\fP { \fBvaso::Side::Left\fP, \fBvaso::Side::Right\fP }"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const \fBuint8\fP \fBDURATION\fP = 6"
.br
.ti -1c
.RI "const \fBsint8\fP \fBERROR\fP = -1"
.br
.ti -1c
.RI "const \fBuint8\fP \fBREC_COUNT\fP = 6"
.br
.ti -1c
.RI "const \fBuint32\fP \fBSAMPLE_COUNT\fP = 262144"
.br
.ti -1c
.RI "const \fBuint16\fP \fBSAMPLE_FREQ\fP = 48000"
.br
.ti -1c
.RI "const std::string \fBTEMP_FILE\fP = '\&.temp'"
.br
.ti -1c
.RI "const \fBuint32\fP \fBBUFFER_SIZE\fP = \fBSAMPLE_COUNT\fP * sizeof(\fBfloat32\fP)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Contains declarations of system-independant (universal size) integers and float types, shortened type names for some commonly used types, and enumerations\&. 


.PP
\fBAuthor:\fP
.RS 4
Samuel Andrew Wisner, awisner94@gmail.com 
.RE
.PP

.PP
Definition in file \fBdefinitions\&.hpp\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define ENUM   signed char"

.PP
Definition at line 16 of file definitions\&.hpp\&.
.SH "Typedef Documentation"
.PP 
.SS "typedef unsigned char \fBbyte\fP"

.PP
Definition at line 20 of file definitions\&.hpp\&.
.SS "typedef std::complex<\fBfloat32\fP> \fBcfloat32\fP"
Complex float32's\&. 
.PP
Definition at line 81 of file definitions\&.hpp\&.
.SS "typedef float \fBfloat32\fP"

.PP
Definition at line 33 of file definitions\&.hpp\&.
.SS "typedef double \fBfloat64\fP"

.PP
Definition at line 34 of file definitions\&.hpp\&.
.SS "typedef signed short \fBsint16\fP"

.PP
Definition at line 25 of file definitions\&.hpp\&.
.SS "typedef signed int \fBsint32\fP"

.PP
Definition at line 28 of file definitions\&.hpp\&.
.SS "typedef signed long long \fBsint64\fP"

.PP
Definition at line 31 of file definitions\&.hpp\&.
.SS "typedef signed char \fBsint8\fP"

.PP
Definition at line 22 of file definitions\&.hpp\&.
.SS "typedef unsigned short \fBuint16\fP"

.PP
Definition at line 24 of file definitions\&.hpp\&.
.SS "typedef unsigned int \fBuint32\fP"

.PP
Definition at line 27 of file definitions\&.hpp\&.
.SS "typedef unsigned long long \fBuint64\fP"

.PP
Definition at line 30 of file definitions\&.hpp\&.
.SS "typedef unsigned char \fBuint8\fP"

.PP
Definition at line 21 of file definitions\&.hpp\&.
.SH "Variable Documentation"
.PP 
.SS "const \fBuint32\fP BUFFER_SIZE = \fBSAMPLE_COUNT\fP * sizeof(\fBfloat32\fP)"
Size of the sample buffer\&. 
.PP
Definition at line 73 of file definitions\&.hpp\&.
.SS "const \fBuint8\fP DURATION = 6"
Duration of recording in seconds\&. 
.PP
Definition at line 42 of file definitions\&.hpp\&.
.SS "const \fBsint8\fP ERROR = -1"
Error integer returned when the program must exit with an error\&. 
.PP
Definition at line 47 of file definitions\&.hpp\&.
.SS "const \fBuint8\fP REC_COUNT = 6"
Number of recordings (both left and right) to make\&. 
.PP
Definition at line 52 of file definitions\&.hpp\&.
.SS "const \fBuint32\fP SAMPLE_COUNT = 262144"
Number of samples to use in processing the recordings\&. Must be a power of two\&. SAMPLE_COUNT / SAMPLE_FREQ < DURATION must be true\&. 
.PP
Definition at line 58 of file definitions\&.hpp\&.
.SS "const \fBuint16\fP SAMPLE_FREQ = 48000"
Recording sampling rate in Hz (NOT kHz)\&. 
.PP
Definition at line 63 of file definitions\&.hpp\&.
.SS "const std::string TEMP_FILE = '\&.temp'"
Filename of the temporary recording file\&. 
.PP
Definition at line 68 of file definitions\&.hpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Andrew and Nick's Project from the source code\&.
