.TH "src/fileio.hpp" 3 "Mon Apr 18 2016" "Andrew and Nick's Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/fileio.hpp \- 
.PP
contains functions related to the file I/O use in this program  

.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <string>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include 'definitions\&.hpp'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBvaso\fP"
.br
.RI "\fIcontains function()s related to the program's threaded processing of audio data \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "std::string \fBvaso::PatientName\fP ()"
.br
.ti -1c
.RI "std::map< Side, \fBDataParams\fP > \fBvaso::ReadParams\fP (auto filename)"
.br
.ti -1c
.RI "std::string \fBvaso::WriteParams\fP (\fBDataParams\fP params, auto filename)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const std::string \fBvaso::CSV_HEADER\fP = 'Time,Side,Frequency,Noise Level'"
.br
.ti -1c
.RI "const std::string \fBvaso::PATIENT_PATH\fP = '/home/pi/patients/'"
.br
.in -1c
.SH "Detailed Description"
.PP 
contains functions related to the file I/O use in this program 


.PP
\fBAuthor:\fP
.RS 4
Samuel Andrew Wisner, awisner94@gmail.com 
.RE
.PP

.PP
Definition in file \fBfileio\&.hpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Andrew and Nick's Project from the source code\&.
