.TH "src/fileio.hpp" 3 "Fri Apr 15 2016" "Andrew and Nick's Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/fileio.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <string>\fP
.br
\fC#include 'definitions\&.hpp'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBvaso\fP"
.br
.RI "\fIcontains functions related to the file I/O use in this program \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "std::string \fBvaso::CurrentDataName\fP ()"
.br
.ti -1c
.RI "std::string \fBvaso::InitialDataName\fP (auto dir)"
.br
.ti -1c
.RI "std::string \fBvaso::PatientName\fP ()"
.br
.ti -1c
.RI "\fBDataParams\fP \fBvaso::ReadParams\fP (auto filename)"
.br
.ti -1c
.RI "std::string \fBvaso::WriteParams\fP (\fBDataParams\fP params, auto filename)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const std::string \fBvaso::PATIENT_PATH\fP = '/home/pi/patients/'"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Andrew and Nick's Project from the source code\&.
