.TH "src/main.cpp" 3 "Wed Mar 30 2016" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/main.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'definitions\&.hpp'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (const char **argv, int argc)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (const char **argv, intargc)"

.PP
Definition at line 13 of file main\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
