.TH "makefile" 3 "Tue Apr 19 2016" "Andrew and Nick's Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
makefile \- 
.PP
Contains recipes for building the test applications, the main application, and the documentation\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Contains recipes for building the test applications, the main application, and the documentation\&. 


.PP
\fBAuthor:\fP
.RS 4
Samuel Andrew Wisner, awisner94@gmail.com 
.RE
.PP

.PP
Definition in file \fBmakefile\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Andrew and Nick's Project from the source code\&.
