.TH "Maximum" 3 "Thu Mar 31 2016" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Maximum \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <definitions\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBfloat32\fP \fBvalue\fP"
.br
.ti -1c
.RI "\fBuint32\fP \fBindex\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Contains the maximum value found in an array and the value's index in that array\&. 
.PP
Definition at line 49 of file definitions\&.hpp\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBuint32\fP Maximum::index"

.PP
Definition at line 51 of file definitions\&.hpp\&.
.SS "\fBfloat32\fP Maximum::value"

.PP
Definition at line 50 of file definitions\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
