.TH "src/process.hpp" 3 "Wed Apr 20 2016" "The Automatic Vasospasm Detection Application" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/process.hpp \- 
.PP
Contains functions related to the program's threaded processing of audio data\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <map>\fP
.br
\fC#include <stdexcept>\fP
.br
\fC#include 'definitions\&.hpp'\fP
.br
\fC#include 'sigmath\&.hpp'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBavda\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBDataParams\fP \fBavda::process\fP (\fBfloat32\fP *data, \fBuint32\fP size, \fBfloat32\fP samplingRate)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Contains functions related to the program's threaded processing of audio data\&. 


.PP
\fBAuthor:\fP
.RS 4
Samuel Andrew Wisner, awisner94@gmail.com 
.RE
.PP

.PP
Definition in file \fBprocess\&.hpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for The Automatic Vasospasm Detection Application from the source code\&.
