.TH "src/process.hpp" 3 "Fri Apr 15 2016" "Andrew and Nick's Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/process.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <map>\fP
.br
\fC#include <stdexcept>\fP
.br
\fC#include 'definitions\&.hpp'\fP
.br
\fC#include 'sigmath\&.hpp'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBvaso\fP"
.br
.RI "\fIcontains functions related to the file I/O use in this program \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "std::map< Side, \fBDataParams\fP > \fBvaso::Process\fP (\fBfloat32\fP data[\fBREC_COUNT\fP][\fBSAMPLE_COUNT\fP])"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Andrew and Nick's Project from the source code\&.
