.TH "src/process.hpp" 3 "Thu Mar 31 2016" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/process.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <map>\fP
.br
\fC#include <stdexcept>\fP
.br
\fC#include 'definitions\&.hpp'\fP
.br
\fC#include 'sigmath\&.hpp'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBvaso\fP"
.br
.RI "\fIcontains functions related to the file I/O use in this program \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "std::map< \fBDataParams\fP > \fBvaso::Process\fP (\fBfloat32\fP *data, \fBuint8\fP recCount, \fBuint32\fP sampleCount, \fBuint32\fP sampleFreq, \fBuint8\fP *counter)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
