.TH "ProcData" 3 "Wed Mar 30 2016" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ProcData \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <definitions\&.hpp>\fP
.SH "Detailed Description"
.PP 
A structure containing information needed in the \fBprocess()\fP thread\&. 
.PP
Definition at line 47 of file definitions\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
