.TH "src/read_params_test.cpp" 3 "Wed Apr 20 2016" "The Automatic Vasospasm Detection Application" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/read_params_test.cpp \- 
.PP
Contains a program test the \fBPatientName()\fP function\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include 'fileio\&.hpp'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Contains a program test the \fBPatientName()\fP function\&. 


.PP
\fBAuthor:\fP
.RS 4
Samuel Andrew Wisner, awisner94@gmail.com 
.RE
.PP

.PP
Definition in file \fBread_params_test\&.cpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "int main (intargc, char **argv)"
Tests the \fBPatientName()\fP function in \fBfileio\&.hpp\fP\&. 
.PP
Definition at line 17 of file read_params_test\&.cpp\&.
.PP
.nf
17                                 {
18     string filename = PatientName();
19     cout << filename;
20 }
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for The Automatic Vasospasm Detection Application from the source code\&.
