.TH "src/sigmath.hpp" 3 "Tue Apr 19 2016" "Andrew and Nick's Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/sigmath.hpp \- 
.PP
contains the functions necessary to perform the mathematical operations required by this program  

.SH SYNOPSIS
.br
.PP
\fC#include <complex>\fP
.br
\fC#include 'definitions\&.hpp'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBvaso\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBvaso::absolute\fP (\fBfloat32\fP *data, \fBuint32\fP size)"
.br
.ti -1c
.RI "\fBfloat32\fP \fBvaso::average\fP (\fBfloat32\fP *data, \fBuint32\fP size)"
.br
.ti -1c
.RI "\fBDataParams\fP \fBvaso::average\fP (\fBDataParams\fP *params, \fBuint8\fP size)"
.br
.ti -1c
.RI "void \fBvaso::decibels\fP (\fBfloat32\fP *data, \fBuint32\fP size)"
.br
.ti -1c
.RI "void \fBvaso::diff\fP (\fBfloat32\fP *data, \fBuint32\fP size)"
.br
.ti -1c
.RI "void \fBvaso::fft\fP (\fBcfloat32\fP *data, \fBuint32\fP size)"
.br
.ti -1c
.RI "void \fBvaso::mag\fP (\fBcfloat32\fP *orig, \fBfloat32\fP *newmags, \fBuint32\fP size)"
.br
.ti -1c
.RI "\fBMaximum\fP \fBvaso::max\fP (\fBfloat32\fP *data, \fBuint32\fP size)"
.br
.ti -1c
.RI "void \fBvaso::smooth\fP (\fBfloat32\fP *data, \fBuint32\fP size, \fBuint16\fP order)"
.br
.in -1c
.SH "Detailed Description"
.PP 
contains the functions necessary to perform the mathematical operations required by this program 


.PP
\fBAuthor:\fP
.RS 4
Samuel Andrew Wisner, awisner94@gmail.com 
.PP
Nicholas K\&. Nolan 
.RE
.PP

.PP
Definition in file \fBsigmath\&.hpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Andrew and Nick's Project from the source code\&.
