.TH "src/sound.hpp" 3 "Mon Apr 18 2016" "Andrew and Nick's Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/sound.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include 'definitions\&.hpp'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBvaso\fP"
.br
.RI "\fIcontains function()s related to the program's threaded processing of audio data \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBvaso::play\fP (auto filename)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Andrew and Nick's Project from the source code\&.
