.TH "ThreadParams" 3 "Fri Apr 15 2016" "Andrew and Nick's Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ThreadParams \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <definitions\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBfloat32\fP ** \fBdata\fP"
.br
.ti -1c
.RI "\fBuint8\fP \fBrecCount\fP"
.br
.ti -1c
.RI "\fBuint32\fP \fBsampleCount\fP"
.br
.ti -1c
.RI "\fBuint32\fP \fBsampleFreq\fP"
.br
.ti -1c
.RI "\fBuint8\fP * \fBcounter\fP"
.br
.ti -1c
.RI "std::map< \fBvaso::Side\fP, \fBDataParams\fP > \fBresults\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Contains the information needed by the thread that executes the \fBProcess()\fP function\&. 
.PP
Definition at line 72 of file definitions\&.hpp\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBuint8\fP* ThreadParams::counter"

.PP
Definition at line 77 of file definitions\&.hpp\&.
.SS "\fBfloat32\fP** ThreadParams::data"

.PP
Definition at line 73 of file definitions\&.hpp\&.
.SS "\fBuint8\fP ThreadParams::recCount"

.PP
Definition at line 74 of file definitions\&.hpp\&.
.SS "std::map<\fBvaso::Side\fP, \fBDataParams\fP> ThreadParams::results"

.PP
Definition at line 78 of file definitions\&.hpp\&.
.SS "\fBuint32\fP ThreadParams::sampleCount"

.PP
Definition at line 75 of file definitions\&.hpp\&.
.SS "\fBuint32\fP ThreadParams::sampleFreq"

.PP
Definition at line 76 of file definitions\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Andrew and Nick's Project from the source code\&.
