.TH "src/threadproc.hpp" 3 "Wed Mar 30 2016" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/threadproc.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <pthread\&.h>\fP
.br
\fC#include 'definitions\&.hpp'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBvaso\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void * \fBvaso::process\fP (void *procdata)"
.br
.ti -1c
.RI "void \fBvaso::StartProcessing\fP (\fBProcData\fP procdata)"
.br
.ti -1c
.RI "void * \fBvaso::processing\fP (void *procdata)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
