\hypertarget{makefile}{\section{makefile File Reference}
\label{makefile}\index{makefile@{makefile}}
}


Contains recipes for building the test applications, the main application, and the documentation.  




\subsection{Detailed Description}
Contains recipes for building the test applications, the main application, and the documentation. 

\begin{DoxyAuthor}{Author}
Samuel Andrew Wisner, \href{mailto:awisner94@gmail.com}{\tt awisner94@gmail.\+com} 
\end{DoxyAuthor}


Definition in file \hyperlink{makefile_source}{makefile}.

